// Phase 15F — renders Phase 15E's committed interpretationNotes verbatim.
// No additional recommendation prose is generated by the UI.

import { Card } from "../../../../components/common";
import { useLocale } from "../../../../i18n/useLocale";

export interface InterpretationNotesProps {
  readonly notes: readonly string[];
}

export function InterpretationNotes({ notes }: InterpretationNotesProps) {
  const { t } = useLocale();
  if (notes.length === 0) return null;

  return (
    <Card title={t("capitalInterpretationNotesTitle")}>
      <ul className="space-y-2 text-sm leading-6 text-slate-600">
        {notes.map((note, index) => (
          <li key={index}>{note}</li>
        ))}
      </ul>
    </Card>
  );
}

export default InterpretationNotes;
