import type {
  EnrollmentTuitionGradeMappingLayerContract,
  EnrollmentTuitionGradeMappingRecord,
} from "./enrollmentTuitionGradeMappingContract";
import type { GradeId } from "./revenueInputs";

// t1 and t2: confirmed 50/50 learner modality mix (full-time + manhã half-period morning).
// tuitionSourceCourseLabel is null for t1/t2 because mapping is a blend, not a single label.
// tuitionNormalizedBand is null for t1/t2 because the two modalities use different bands.
// Remaining 15 grades: direct 1-to-1 mapping, fully resolved.
// All 17 records have calculationReady: false — Receita formula requires explicit approval.

const GRADE_MAPPING_RECORDS: Record<
  GradeId,
  EnrollmentTuitionGradeMappingRecord
> = {
  t1: {
    enrollmentGradeId: "t1",
    enrollmentGradeLabel: "Toddlers 1",
    tuitionSourceCourseLabel: null,
    tuitionNormalizedGrade: "Toddler 1",
    tuitionNormalizedBand: null,
    tuitionDivision: "Early Years",
    tuitionModality: null,
    mappingStatus: "mapped",
    needsFinanceReview: false,
    toddlerModalityMix: {
      fullTimeCourseLabel: "TODDLERS 1",
      halfPeriodMorningCourseLabel: "TODDLERS 1 - m",
      fullTimeLearnerShare: 0.5,
      halfPeriodMorningLearnerShare: 0.5,
      blendedCalculationBasis: "weighted_blend_of_source_annualGrossContractValueBRL",
      observedHalfPeriodMorningPriceRatioToFullTime: 0.585,
      observedRatioIsValidationNoteOnly: true,
      halfPeriodMorningPricingSource: "independent_source_record_not_derived_from_full_time",
      assumptionStatus: "confirmed",
      assumptionSource:
        "Head of Finance: Rio offers both toddler modalities. 50% of T1 enrollment is full-time (TODDLERS 1) and 50% is manhã half-period morning (TODDLERS 1 - m). Confirmed 2026-06-02.",
    },
    sourceNotes:
      "Both toddler modalities are active at Rio. 50% of T1 enrollment is full-time (TODDLERS 1) and 50% is manhã half-period morning (TODDLERS 1 - m). The 50/50 assumption is a learner modality mix, not a tuition discount. Half-period morning tuition is an independent tuition source record and is approximately 58.5% of full-time tuition (observed across all 3 BP scenarios). Calculation basis: 0.50 × TODDLERS_1_annualGrossContractValueBRL + 0.50 × TODDLERS_1_M_annualGrossContractValueBRL from tuitionSourceData.ts source records. The 58.5% ratio is a validation note only — source records are used directly, not derived from full-time price.",
    calculationReady: false,
  },
  t2: {
    enrollmentGradeId: "t2",
    enrollmentGradeLabel: "Toddlers 2",
    tuitionSourceCourseLabel: null,
    tuitionNormalizedGrade: "Toddler 2",
    tuitionNormalizedBand: null,
    tuitionDivision: "Early Years",
    tuitionModality: null,
    mappingStatus: "mapped",
    needsFinanceReview: false,
    toddlerModalityMix: {
      fullTimeCourseLabel: "TODDLERS 2",
      halfPeriodMorningCourseLabel: "TODDLERS 2 - m",
      fullTimeLearnerShare: 0.5,
      halfPeriodMorningLearnerShare: 0.5,
      blendedCalculationBasis: "weighted_blend_of_source_annualGrossContractValueBRL",
      observedHalfPeriodMorningPriceRatioToFullTime: 0.585,
      observedRatioIsValidationNoteOnly: true,
      halfPeriodMorningPricingSource: "independent_source_record_not_derived_from_full_time",
      assumptionStatus: "confirmed",
      assumptionSource:
        "Head of Finance: Rio offers both toddler modalities. 50% of T2 enrollment is full-time (TODDLERS 2) and 50% is manhã half-period morning (TODDLERS 2 - m). Confirmed 2026-06-02.",
    },
    sourceNotes:
      "Both toddler modalities are active at Rio. 50% of T2 enrollment is full-time (TODDLERS 2) and 50% is manhã half-period morning (TODDLERS 2 - m). The 50/50 assumption is a learner modality mix, not a tuition discount. Half-period morning tuition is an independent tuition source record and is approximately 58.5% of full-time tuition (observed across all 3 BP scenarios). Calculation basis: 0.50 × TODDLERS_2_annualGrossContractValueBRL + 0.50 × TODDLERS_2_M_annualGrossContractValueBRL from tuitionSourceData.ts source records. The 58.5% ratio is a validation note only — source records are used directly, not derived from full-time price.",
    calculationReady: false,
  },
  pk3: {
    enrollmentGradeId: "pk3",
    enrollmentGradeLabel: "Pre-K3",
    tuitionSourceCourseLabel: "PRE-K3",
    tuitionNormalizedGrade: "Pre-K3",
    tuitionNormalizedBand: "ey_full_day",
    tuitionDivision: "Early Years",
    tuitionModality: "full_day",
    mappingStatus: "mapped",
    needsFinanceReview: false,
    sourceNotes: "Direct 1-to-1 mapping. Enrollment 'Pre-K3' maps unambiguously to tuition source 'PRE-K3'.",
    calculationReady: false,
  },
  pk4: {
    enrollmentGradeId: "pk4",
    enrollmentGradeLabel: "Pre-K4",
    tuitionSourceCourseLabel: "PRE-K4",
    tuitionNormalizedGrade: "Pre-K4",
    tuitionNormalizedBand: "ey_full_day",
    tuitionDivision: "Early Years",
    tuitionModality: "full_day",
    mappingStatus: "mapped",
    needsFinanceReview: false,
    sourceNotes: "Direct 1-to-1 mapping. Enrollment 'Pre-K4' maps unambiguously to tuition source 'PRE-K4'.",
    calculationReady: false,
  },
  kindergarten: {
    enrollmentGradeId: "kindergarten",
    enrollmentGradeLabel: "Kindergarten",
    tuitionSourceCourseLabel: "KINDERGARTEN",
    tuitionNormalizedGrade: "Kindergarten",
    tuitionNormalizedBand: "ey_full_day",
    tuitionDivision: "Early Years",
    tuitionModality: "full_day",
    mappingStatus: "mapped",
    needsFinanceReview: false,
    sourceNotes: "Direct 1-to-1 mapping. Enrollment 'Kindergarten' maps unambiguously to tuition source 'KINDERGARTEN'.",
    calculationReady: false,
  },
  g1: {
    enrollmentGradeId: "g1",
    enrollmentGradeLabel: "Grade 1",
    tuitionSourceCourseLabel: "GRADE 1",
    tuitionNormalizedGrade: "Grade 1",
    tuitionNormalizedBand: "lower_school",
    tuitionDivision: "Lower School",
    tuitionModality: "full_day",
    mappingStatus: "mapped",
    needsFinanceReview: false,
    sourceNotes: "Direct 1-to-1 mapping. Enrollment 'Grade 1' maps unambiguously to tuition source 'GRADE 1'.",
    calculationReady: false,
  },
  g2: {
    enrollmentGradeId: "g2",
    enrollmentGradeLabel: "Grade 2",
    tuitionSourceCourseLabel: "GRADE 2",
    tuitionNormalizedGrade: "Grade 2",
    tuitionNormalizedBand: "lower_school",
    tuitionDivision: "Lower School",
    tuitionModality: "full_day",
    mappingStatus: "mapped",
    needsFinanceReview: false,
    sourceNotes: "Direct 1-to-1 mapping. Enrollment 'Grade 2' maps unambiguously to tuition source 'GRADE 2'.",
    calculationReady: false,
  },
  g3: {
    enrollmentGradeId: "g3",
    enrollmentGradeLabel: "Grade 3",
    tuitionSourceCourseLabel: "GRADE 3",
    tuitionNormalizedGrade: "Grade 3",
    tuitionNormalizedBand: "lower_school",
    tuitionDivision: "Lower School",
    tuitionModality: "full_day",
    mappingStatus: "mapped",
    needsFinanceReview: false,
    sourceNotes: "Direct 1-to-1 mapping. Enrollment 'Grade 3' maps unambiguously to tuition source 'GRADE 3'.",
    calculationReady: false,
  },
  g4: {
    enrollmentGradeId: "g4",
    enrollmentGradeLabel: "Grade 4",
    tuitionSourceCourseLabel: "GRADE 4",
    tuitionNormalizedGrade: "Grade 4",
    tuitionNormalizedBand: "lower_school",
    tuitionDivision: "Lower School",
    tuitionModality: "full_day",
    mappingStatus: "mapped",
    needsFinanceReview: false,
    sourceNotes: "Direct 1-to-1 mapping. Enrollment 'Grade 4' maps unambiguously to tuition source 'GRADE 4'.",
    calculationReady: false,
  },
  g5: {
    enrollmentGradeId: "g5",
    enrollmentGradeLabel: "Grade 5",
    tuitionSourceCourseLabel: "GRADE 5",
    tuitionNormalizedGrade: "Grade 5",
    tuitionNormalizedBand: "lower_school",
    tuitionDivision: "Lower School",
    tuitionModality: "full_day",
    mappingStatus: "mapped",
    needsFinanceReview: false,
    sourceNotes: "Direct 1-to-1 mapping. Enrollment 'Grade 5' maps unambiguously to tuition source 'GRADE 5'.",
    calculationReady: false,
  },
  g6: {
    enrollmentGradeId: "g6",
    enrollmentGradeLabel: "Grade 6",
    tuitionSourceCourseLabel: "GRADE 6",
    tuitionNormalizedGrade: "Grade 6",
    tuitionNormalizedBand: "middle_school",
    tuitionDivision: "Middle School",
    tuitionModality: "full_day",
    mappingStatus: "mapped",
    needsFinanceReview: false,
    sourceNotes: "Direct 1-to-1 mapping. Enrollment 'Grade 6' maps unambiguously to tuition source 'GRADE 6'.",
    calculationReady: false,
  },
  g7: {
    enrollmentGradeId: "g7",
    enrollmentGradeLabel: "Grade 7",
    tuitionSourceCourseLabel: "GRADE 7",
    tuitionNormalizedGrade: "Grade 7",
    tuitionNormalizedBand: "middle_school",
    tuitionDivision: "Middle School",
    tuitionModality: "full_day",
    mappingStatus: "mapped",
    needsFinanceReview: false,
    sourceNotes: "Direct 1-to-1 mapping. Enrollment 'Grade 7' maps unambiguously to tuition source 'GRADE 7'.",
    calculationReady: false,
  },
  g8: {
    enrollmentGradeId: "g8",
    enrollmentGradeLabel: "Grade 8",
    tuitionSourceCourseLabel: "GRADE 8",
    tuitionNormalizedGrade: "Grade 8",
    tuitionNormalizedBand: "middle_school",
    tuitionDivision: "Middle School",
    tuitionModality: "full_day",
    mappingStatus: "mapped",
    needsFinanceReview: false,
    sourceNotes: "Direct 1-to-1 mapping. Enrollment 'Grade 8' maps unambiguously to tuition source 'GRADE 8'.",
    calculationReady: false,
  },
  g9: {
    enrollmentGradeId: "g9",
    enrollmentGradeLabel: "Grade 9",
    tuitionSourceCourseLabel: "GRADE 9",
    tuitionNormalizedGrade: "Grade 9",
    tuitionNormalizedBand: "high_school",
    tuitionDivision: "High School",
    tuitionModality: "full_day",
    mappingStatus: "mapped",
    needsFinanceReview: false,
    sourceNotes: "Direct 1-to-1 mapping. Enrollment 'Grade 9' maps unambiguously to tuition source 'GRADE 9'.",
    calculationReady: false,
  },
  g10: {
    enrollmentGradeId: "g10",
    enrollmentGradeLabel: "Grade 10",
    tuitionSourceCourseLabel: "GRADE 10",
    tuitionNormalizedGrade: "Grade 10",
    tuitionNormalizedBand: "high_school",
    tuitionDivision: "High School",
    tuitionModality: "full_day",
    mappingStatus: "mapped",
    needsFinanceReview: false,
    sourceNotes: "Direct 1-to-1 mapping. Enrollment 'Grade 10' maps unambiguously to tuition source 'GRADE 10'.",
    calculationReady: false,
  },
  g11: {
    enrollmentGradeId: "g11",
    enrollmentGradeLabel: "Grade 11",
    tuitionSourceCourseLabel: "GRADE 11",
    tuitionNormalizedGrade: "Grade 11",
    tuitionNormalizedBand: "high_school",
    tuitionDivision: "High School",
    tuitionModality: "full_day",
    mappingStatus: "mapped",
    needsFinanceReview: false,
    sourceNotes: "Direct 1-to-1 mapping. Enrollment 'Grade 11' maps unambiguously to tuition source 'GRADE 11'.",
    calculationReady: false,
  },
  g12: {
    enrollmentGradeId: "g12",
    enrollmentGradeLabel: "Grade 12",
    tuitionSourceCourseLabel: "GRADE 12",
    tuitionNormalizedGrade: "Grade 12",
    tuitionNormalizedBand: "high_school",
    tuitionDivision: "High School",
    tuitionModality: "full_day",
    mappingStatus: "mapped",
    needsFinanceReview: false,
    sourceNotes: "Direct 1-to-1 mapping. Enrollment 'Grade 12' maps unambiguously to tuition source 'GRADE 12'.",
    calculationReady: false,
  },
} satisfies Record<GradeId, EnrollmentTuitionGradeMappingRecord>;

// 17 records: 17 mapped (t1/t2 via confirmed 50/50 learner modality blend; pk3–g12 direct 1-to-1).
// All records calculationReady: false — Receita formula requires explicit approval.
export const ENROLLMENT_TUITION_GRADE_MAPPING: EnrollmentTuitionGradeMappingLayerContract =
  {
    layerReadiness: "fully_represented",
    receitaCalculationReady: false,
    receitaBlockerReason:
      "All 17 grade mappings are fully represented. T1 (Toddlers 1) and T2 (Toddlers 2) use a Finance-confirmed 50/50 learner modality mix: blendedValue = 0.50 × fullTimeAnnualGrossContractValueBRL + 0.50 × halfPeriodMorningAnnualGrossContractValueBRL, using source records from tuitionSourceData.ts. Remaining blocker: Receita formula implementation has not been approved. Calculation cannot begin until the Receita formula design is explicitly approved.",
    mappedCount: 17,
    needsReviewCount: 0,
    blockedCount: 0,
    records: GRADE_MAPPING_RECORDS,
    notes:
      "Crosswalk between enrollment GradeId keys (Opening Grades / Occupancy source layer, revenueInputs.ts) and tuition source course labels (tuitionSourceData.ts, tuitionSourceDataContract.ts). No BRL values. No calculations. All 17 GradeIds are represented. T1/T2 use a confirmed blended modality approach — tuitionSourceCourseLabel is null (blend of two source records); tuitionNormalizedBand is null (different bands per modality); tuitionDivision is 'Early Years' (same for both modalities). calculationReady is false for all records because the Receita formula implementation has not been approved.",
  };
