import type {
  PayrollRoleCostSourceDataContract,
  PayrollRoleCostSourceRecord,
} from "./payrollRoleCostSourceDataContract";

export const PAYROLL_ROLE_COST_SOURCE_DATA: PayrollRoleCostSourceDataContract =
  {
    extractedAt: "2026-06-03",
    extractedBy:
      "Phase 8A source extraction — Rio Scenario Resilience Simulator",
    sourceDiscoveryNotes:
      "No Finance-deposited Payroll spreadsheet or Folha de Pagamento workbook tab was found in this repository (5 xlsx files inspected: 4 Modelo_Ocupacao occupancy workbooks and 1 HS schedule reference — none contain payroll cost data). Role cost evidence was extracted from the existing app source constants which were previously reviewed by Finance: src/constants/leadership.ts (Leadership, Backoffice, Specialists) and src/constants/teaching.ts (teaching tiers and support inputs). The audit file src/data/rio-simulator/currentRoles.audit.json (generated 2026-05-29) was consulted for structural reference only. Finance validation confirmed by Luciana as prior Finance review of existing role/payroll numbers. Role cost values (grossMonthly, laborChargesMonthly, benefitsMonthly) are considered Finance-validated; however, calculationReady remains false because section counts, staffing mapping, Org Design activation, and section-handling rules are not yet approved for the simulator.",
    primarySourceFile: "src/constants/leadership.ts",
    secondarySourceFile: "src/constants/teaching.ts",
    auditReferenceFile: "src/data/rio-simulator/currentRoles.audit.json",
    noFinancePayrollSpreadsheetFound: true,
    financeValidationProvenance:
      "Finance validation confirmed by Luciana as prior Finance review of existing role/payroll numbers.",
    allRecordsNeedFinanceReview: false,
    annualizationFormulaFromCore:
      "(grossMonthly + laborChargesMonthly) * 13 + benefitsMonthly * 12",
    annualizationFormulaSource:
      "src/lib/payroll/core.ts — annualSalaryBurden() — withBenefits=true path",
    annualAdjustmentFactor:
      "1.06 per year compound from 2028 (ANNUAL_ADJUSTMENT in src/constants/index.ts); applied in projection utilities, not stored in raw cost records",
    extractionBoundaries: {
      included: [
        "Role-level records from LEADERSHIP_CONFIG (Leadership layer B): 8 roles",
        "Role-level records from BACKOFFICE_CONFIG (Backoffice layer C): 12 roles",
        "Role-level records from SPECIALISTS_CONFIG (Specialists layer D): 6 roles",
        "Teaching tier compensation inputs from EDUCATOR_LEVELS (TeachingTier): 5 inputs",
        "Teaching support inputs from LEARNING_ASSISTANT_DETAIL and LEARNING_MONITOR_DETAIL (TeachingSupport): 2 inputs",
      ],
      excluded: [
        "Display-only archetypes (STEM Specialist, Humanities Specialist, Signature Programs Specialist, Bilingual Specialist) — no salary or FTE data",
        "Org design extension roles from orgDesignOptions.ts — not wired to payroll, no validated cost data",
        "Annual derived values — annualSalaryBRL and annualTotalCostBRL are null (computed, not stored in source)",
      ],
    },
    sourceCategoryTotals: {
      leadershipRolesLayerB: 8,
      backofficeRolesLayerC: 12,
      specialistRolesLayerD: 6,
      teachingTierInputs: 5,
      teachingSupportInputs: 2,
      displayOnlyExcluded: 4,
      totalRecords: 33,
    },
    records: [
      // ── LEADERSHIP (Layer B) ─────────────────────────────────────────────
      {
        sourceRoleLabel: "Head of School",
        normalizedRoleId: "hos",
        roleFamily: "Leadership",
        layer: "B",
        regime: null,
        division: null,
        areaOrFunction: "Leadership",
        gradeBandApplicability: null,
        yearApplicability: 2028,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: "1 from 2028",
        headcountProgression: [[2028, 1]],
        rawGrossMonthlyBRL: 51167.45,
        rawLaborChargesMonthlyBRL: 24816.21,
        rawBenefitsMonthlyBRL: 1464.28,
        monthlySalaryBRL: 51167.45,
        monthlyTotalCostBRL: null,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOLHA_DIRETA",
        benefitsOrChargesNotes:
          "Source stores three separate monthly components: rawGrossMonthlyBRL (salary only), rawLaborChargesMonthlyBRL (encargos), rawBenefitsMonthlyBRL (benefícios). Annualization: (grossMonthly + laborChargesMonthly) × 13 + benefitsMonthly × 12 per src/lib/payroll/core.ts.",
        sourceFile: "src/constants/leadership.ts",
        sourceSheetOrTab: "LEADERSHIP_CONFIG",
        sourceRowOrCellRef: "LEADERSHIP_CONFIG[0]",
        sourceNotes:
          "Campus-wide executive role. Headcount flat at 1 from 2028. No division assignment in source.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "EY Coordinator",
        normalizedRoleId: "ey_principal",
        roleFamily: "Leadership",
        layer: "B",
        regime: null,
        division: "Early Years",
        areaOrFunction: "Leadership",
        gradeBandApplicability: null,
        yearApplicability: 2028,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: "1 from 2028",
        headcountProgression: [[2028, 1]],
        rawGrossMonthlyBRL: 19941.74,
        rawLaborChargesMonthlyBRL: 9671.74,
        rawBenefitsMonthlyBRL: 1331.93,
        monthlySalaryBRL: 19941.74,
        monthlyTotalCostBRL: null,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOLHA_DIRETA",
        benefitsOrChargesNotes:
          "Three separate monthly components in source. See rawGrossMonthlyBRL, rawLaborChargesMonthlyBRL, rawBenefitsMonthlyBRL.",
        sourceFile: "src/constants/leadership.ts",
        sourceSheetOrTab: "LEADERSHIP_CONFIG",
        sourceRowOrCellRef: "LEADERSHIP_CONFIG[1]",
        sourceNotes:
          "Division inferred from role label ('EY Coordinator'). Source does not store an explicit division field.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "LS Coordinator",
        normalizedRoleId: "ls_principal",
        roleFamily: "Leadership",
        layer: "B",
        regime: null,
        division: "Lower School",
        areaOrFunction: "Leadership",
        gradeBandApplicability: null,
        yearApplicability: 2028,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: "1 from 2028",
        headcountProgression: [[2028, 1]],
        rawGrossMonthlyBRL: 19941.74,
        rawLaborChargesMonthlyBRL: 9671.74,
        rawBenefitsMonthlyBRL: 1331.93,
        monthlySalaryBRL: 19941.74,
        monthlyTotalCostBRL: null,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOLHA_DIRETA",
        benefitsOrChargesNotes:
          "Three separate monthly components in source. See rawGrossMonthlyBRL, rawLaborChargesMonthlyBRL, rawBenefitsMonthlyBRL.",
        sourceFile: "src/constants/leadership.ts",
        sourceSheetOrTab: "LEADERSHIP_CONFIG",
        sourceRowOrCellRef: "LEADERSHIP_CONFIG[2]",
        sourceNotes:
          "Division inferred from role label ('LS Coordinator'). Source does not store an explicit division field.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "MS Coordinator",
        normalizedRoleId: "ms_principal",
        roleFamily: "Leadership",
        layer: "B",
        regime: null,
        division: "Middle School",
        areaOrFunction: "Leadership",
        gradeBandApplicability: null,
        yearApplicability: 2031,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: "1 from 2031",
        headcountProgression: [[2031, 1]],
        rawGrossMonthlyBRL: 19941.74,
        rawLaborChargesMonthlyBRL: 9671.74,
        rawBenefitsMonthlyBRL: 1331.93,
        monthlySalaryBRL: 19941.74,
        monthlyTotalCostBRL: null,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOLHA_DIRETA",
        benefitsOrChargesNotes:
          "Three separate monthly components in source. See rawGrossMonthlyBRL, rawLaborChargesMonthlyBRL, rawBenefitsMonthlyBRL.",
        sourceFile: "src/constants/leadership.ts",
        sourceSheetOrTab: "LEADERSHIP_CONFIG",
        sourceRowOrCellRef: "LEADERSHIP_CONFIG[3]",
        sourceNotes:
          "Activated when Middle School opens (2031). Division inferred from role label.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "HS Coordinator",
        normalizedRoleId: "hs_principal",
        roleFamily: "Leadership",
        layer: "B",
        regime: null,
        division: "High School",
        areaOrFunction: "Leadership",
        gradeBandApplicability: null,
        yearApplicability: 2034,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: "1 from 2034",
        headcountProgression: [[2034, 1]],
        rawGrossMonthlyBRL: 19941.74,
        rawLaborChargesMonthlyBRL: 9671.74,
        rawBenefitsMonthlyBRL: 1331.93,
        monthlySalaryBRL: 19941.74,
        monthlyTotalCostBRL: null,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOLHA_DIRETA",
        benefitsOrChargesNotes:
          "Three separate monthly components in source. See rawGrossMonthlyBRL, rawLaborChargesMonthlyBRL, rawBenefitsMonthlyBRL.",
        sourceFile: "src/constants/leadership.ts",
        sourceSheetOrTab: "LEADERSHIP_CONFIG",
        sourceRowOrCellRef: "LEADERSHIP_CONFIG[4]",
        sourceNotes:
          "Activated when High School opens (2034). Division inferred from role label.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "Counselor",
        normalizedRoleId: "counselor",
        roleFamily: "Leadership",
        layer: "B",
        regime: null,
        division: null,
        areaOrFunction: "Leadership",
        gradeBandApplicability: null,
        yearApplicability: 2028,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: "3 from 2028; 4 from 2031",
        headcountProgression: [
          [2028, 3],
          [2031, 4],
        ],
        rawGrossMonthlyBRL: 16923.84,
        rawLaborChargesMonthlyBRL: 8208.06,
        rawBenefitsMonthlyBRL: 1159.82,
        monthlySalaryBRL: 16923.84,
        monthlyTotalCostBRL: null,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOLHA_DIRETA",
        benefitsOrChargesNotes:
          "Three separate monthly components in source. See rawGrossMonthlyBRL, rawLaborChargesMonthlyBRL, rawBenefitsMonthlyBRL.",
        sourceFile: "src/constants/leadership.ts",
        sourceSheetOrTab: "LEADERSHIP_CONFIG",
        sourceRowOrCellRef: "LEADERSHIP_CONFIG[5]",
        sourceNotes:
          "Campus-wide counseling. Headcount ramp: 3 from 2028, 4 from 2031. Finance review should confirm whether headcount ramp is still current.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "Ed Tech Coordinator",
        normalizedRoleId: "edtech",
        roleFamily: "Leadership",
        layer: "B",
        regime: null,
        division: null,
        areaOrFunction: "Leadership",
        gradeBandApplicability: null,
        yearApplicability: 2028,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: "1 from 2028",
        headcountProgression: [[2028, 1]],
        rawGrossMonthlyBRL: 18493.59,
        rawLaborChargesMonthlyBRL: 8969.39,
        rawBenefitsMonthlyBRL: 1173.58,
        monthlySalaryBRL: 18493.59,
        monthlyTotalCostBRL: null,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOLHA_DIRETA",
        benefitsOrChargesNotes:
          "Three separate monthly components in source. See rawGrossMonthlyBRL, rawLaborChargesMonthlyBRL, rawBenefitsMonthlyBRL.",
        sourceFile: "src/constants/leadership.ts",
        sourceSheetOrTab: "LEADERSHIP_CONFIG",
        sourceRowOrCellRef: "LEADERSHIP_CONFIG[6]",
        sourceNotes:
          "Abbreviated label in source ('Ed Tech Coordinator'). Audit flags naming ambiguity.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "Ops Coordinator",
        normalizedRoleId: "ops",
        roleFamily: "Leadership",
        layer: "B",
        regime: null,
        division: null,
        areaOrFunction: "Leadership",
        gradeBandApplicability: null,
        yearApplicability: 2028,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: "1 from 2028",
        headcountProgression: [[2028, 1]],
        rawGrossMonthlyBRL: 11340.0,
        rawLaborChargesMonthlyBRL: 5499.9,
        rawBenefitsMonthlyBRL: 1143.26,
        monthlySalaryBRL: 11340.0,
        monthlyTotalCostBRL: null,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOLHA_DIRETA",
        benefitsOrChargesNotes:
          "Three separate monthly components in source. See rawGrossMonthlyBRL, rawLaborChargesMonthlyBRL, rawBenefitsMonthlyBRL.",
        sourceFile: "src/constants/leadership.ts",
        sourceSheetOrTab: "LEADERSHIP_CONFIG",
        sourceRowOrCellRef: "LEADERSHIP_CONFIG[7]",
        sourceNotes:
          "Operations/facilities coordination. Campus-wide. Abbreviated label in source.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      // ── BACKOFFICE (Layer C) ─────────────────────────────────────────────
      {
        sourceRoleLabel: "Clerk (Portaria)",
        normalizedRoleId: "clerk",
        roleFamily: "Backoffice",
        layer: "C",
        regime: null,
        division: null,
        areaOrFunction: "Backoffice",
        gradeBandApplicability: null,
        yearApplicability: 2028,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: "4 from 2028",
        headcountProgression: [[2028, 4]],
        rawGrossMonthlyBRL: 2786.75,
        rawLaborChargesMonthlyBRL: 1351.57,
        rawBenefitsMonthlyBRL: 839.17,
        monthlySalaryBRL: 2786.75,
        monthlyTotalCostBRL: null,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOLHA_DIRETA",
        benefitsOrChargesNotes:
          "Three separate monthly components in source. See rawGrossMonthlyBRL, rawLaborChargesMonthlyBRL, rawBenefitsMonthlyBRL.",
        sourceFile: "src/constants/leadership.ts",
        sourceSheetOrTab: "BACKOFFICE_CONFIG",
        sourceRowOrCellRef: "BACKOFFICE_CONFIG[0]",
        sourceNotes:
          "Mixed-language label ('Clerk (Portaria)'). 4 headcount from launch. Audit flags label normalization.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "Family Engagement Analyst",
        normalizedRoleId: "family",
        roleFamily: "Backoffice",
        layer: "C",
        regime: null,
        division: null,
        areaOrFunction: "Backoffice",
        gradeBandApplicability: null,
        yearApplicability: 2028,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: "1 from 2028",
        headcountProgression: [[2028, 1]],
        rawGrossMonthlyBRL: 5335.05,
        rawLaborChargesMonthlyBRL: 2587.5,
        rawBenefitsMonthlyBRL: 849.97,
        monthlySalaryBRL: 5335.05,
        monthlyTotalCostBRL: null,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOLHA_DIRETA",
        benefitsOrChargesNotes:
          "Three separate monthly components in source. See rawGrossMonthlyBRL, rawLaborChargesMonthlyBRL, rawBenefitsMonthlyBRL.",
        sourceFile: "src/constants/leadership.ts",
        sourceSheetOrTab: "BACKOFFICE_CONFIG",
        sourceRowOrCellRef: "BACKOFFICE_CONFIG[1]",
        sourceNotes: "Campus-wide family engagement function.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "Inspirationeer",
        normalizedRoleId: "library",
        roleFamily: "Backoffice",
        layer: "C",
        regime: null,
        division: null,
        areaOrFunction: "Backoffice",
        gradeBandApplicability: null,
        yearApplicability: 2028,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: "1 from 2028",
        headcountProgression: [[2028, 1]],
        rawGrossMonthlyBRL: 6880.65,
        rawLaborChargesMonthlyBRL: 3337.12,
        rawBenefitsMonthlyBRL: 506.52,
        monthlySalaryBRL: 6880.65,
        monthlyTotalCostBRL: null,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOLHA_DIRETA",
        benefitsOrChargesNotes:
          "Three separate monthly components in source. See rawGrossMonthlyBRL, rawLaborChargesMonthlyBRL, rawBenefitsMonthlyBRL.",
        sourceFile: "src/constants/leadership.ts",
        sourceSheetOrTab: "BACKOFFICE_CONFIG",
        sourceRowOrCellRef: "BACKOFFICE_CONFIG[2]",
        sourceNotes:
          "Brand-style role label (roleId=library). Audit flags naming as non-conventional. Finance review should confirm role scope.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "IT Technician",
        normalizedRoleId: "it",
        roleFamily: "Backoffice",
        layer: "C",
        regime: null,
        division: null,
        areaOrFunction: "Backoffice",
        gradeBandApplicability: null,
        yearApplicability: 2028,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: "1 from 2028; 2 from 2032",
        headcountProgression: [
          [2028, 1],
          [2032, 2],
        ],
        rawGrossMonthlyBRL: 6405.0,
        rawLaborChargesMonthlyBRL: 3106.43,
        rawBenefitsMonthlyBRL: 504.51,
        monthlySalaryBRL: 6405.0,
        monthlyTotalCostBRL: null,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOLHA_DIRETA",
        benefitsOrChargesNotes:
          "Three separate monthly components in source. See rawGrossMonthlyBRL, rawLaborChargesMonthlyBRL, rawBenefitsMonthlyBRL.",
        sourceFile: "src/constants/leadership.ts",
        sourceSheetOrTab: "BACKOFFICE_CONFIG",
        sourceRowOrCellRef: "BACKOFFICE_CONFIG[3]",
        sourceNotes: "Headcount ramp: 1 from 2028, 2 from 2032.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "Maintenance Technician",
        normalizedRoleId: "maintenance",
        roleFamily: "Backoffice",
        layer: "C",
        regime: null,
        division: null,
        areaOrFunction: "Backoffice",
        gradeBandApplicability: null,
        yearApplicability: 2028,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: "2 from 2028; 3 from 2036",
        headcountProgression: [
          [2028, 2],
          [2036, 3],
        ],
        rawGrossMonthlyBRL: 3878.7,
        rawLaborChargesMonthlyBRL: 1881.17,
        rawBenefitsMonthlyBRL: 843.8,
        monthlySalaryBRL: 3878.7,
        monthlyTotalCostBRL: null,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOLHA_DIRETA",
        benefitsOrChargesNotes:
          "Three separate monthly components in source. See rawGrossMonthlyBRL, rawLaborChargesMonthlyBRL, rawBenefitsMonthlyBRL.",
        sourceFile: "src/constants/leadership.ts",
        sourceSheetOrTab: "BACKOFFICE_CONFIG",
        sourceRowOrCellRef: "BACKOFFICE_CONFIG[4]",
        sourceNotes: "Headcount ramp: 2 from 2028, 3 from 2036.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "Marketing & Events Analyst",
        normalizedRoleId: "marketing",
        roleFamily: "Backoffice",
        layer: "C",
        regime: null,
        division: null,
        areaOrFunction: "Backoffice",
        gradeBandApplicability: null,
        yearApplicability: 2028,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: "1 from 2028",
        headcountProgression: [[2028, 1]],
        rawGrossMonthlyBRL: 6195.0,
        rawLaborChargesMonthlyBRL: 3004.58,
        rawBenefitsMonthlyBRL: 503.62,
        monthlySalaryBRL: 6195.0,
        monthlyTotalCostBRL: null,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOLHA_DIRETA",
        benefitsOrChargesNotes:
          "Three separate monthly components in source. See rawGrossMonthlyBRL, rawLaborChargesMonthlyBRL, rawBenefitsMonthlyBRL.",
        sourceFile: "src/constants/leadership.ts",
        sourceSheetOrTab: "BACKOFFICE_CONFIG",
        sourceRowOrCellRef: "BACKOFFICE_CONFIG[5]",
        sourceNotes: "Campus-wide marketing and events function.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "Nurse Technician",
        normalizedRoleId: "nurse",
        roleFamily: "Backoffice",
        layer: "C",
        regime: null,
        division: null,
        areaOrFunction: "Backoffice",
        gradeBandApplicability: null,
        yearApplicability: 2028,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: "1 from 2028; 2 from 2035",
        headcountProgression: [
          [2028, 1],
          [2035, 2],
        ],
        rawGrossMonthlyBRL: 3780.0,
        rawLaborChargesMonthlyBRL: 1833.3,
        rawBenefitsMonthlyBRL: 843.38,
        monthlySalaryBRL: 3780.0,
        monthlyTotalCostBRL: null,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOLHA_DIRETA",
        benefitsOrChargesNotes:
          "Three separate monthly components in source. See rawGrossMonthlyBRL, rawLaborChargesMonthlyBRL, rawBenefitsMonthlyBRL.",
        sourceFile: "src/constants/leadership.ts",
        sourceSheetOrTab: "BACKOFFICE_CONFIG",
        sourceRowOrCellRef: "BACKOFFICE_CONFIG[6]",
        sourceNotes: "Headcount ramp: 1 from 2028, 2 from 2035.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "Nursing Intern",
        normalizedRoleId: "nursing_intern",
        roleFamily: "Backoffice",
        layer: "C",
        regime: null,
        division: null,
        areaOrFunction: "Backoffice",
        gradeBandApplicability: null,
        yearApplicability: 2028,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: "1 from 2028",
        headcountProgression: [[2028, 1]],
        rawGrossMonthlyBRL: 1578.0,
        rawLaborChargesMonthlyBRL: 765.33,
        rawBenefitsMonthlyBRL: 834.04,
        monthlySalaryBRL: 1578.0,
        monthlyTotalCostBRL: null,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOLHA_DIRETA",
        benefitsOrChargesNotes:
          "Three separate monthly components in source. See rawGrossMonthlyBRL, rawLaborChargesMonthlyBRL, rawBenefitsMonthlyBRL.",
        sourceFile: "src/constants/leadership.ts",
        sourceSheetOrTab: "BACKOFFICE_CONFIG",
        sourceRowOrCellRef: "BACKOFFICE_CONFIG[7]",
        sourceNotes:
          "Nursing intern. Finance review should confirm employment contract type.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "Financial Analyst",
        normalizedRoleId: "finance",
        roleFamily: "Backoffice",
        layer: "C",
        regime: null,
        division: null,
        areaOrFunction: "Backoffice",
        gradeBandApplicability: null,
        yearApplicability: 2028,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: "2 from 2028",
        headcountProgression: [[2028, 2]],
        rawGrossMonthlyBRL: 5090.0,
        rawLaborChargesMonthlyBRL: 2468.65,
        rawBenefitsMonthlyBRL: 848.93,
        monthlySalaryBRL: 5090.0,
        monthlyTotalCostBRL: null,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOLHA_DIRETA",
        benefitsOrChargesNotes:
          "Three separate monthly components in source. See rawGrossMonthlyBRL, rawLaborChargesMonthlyBRL, rawBenefitsMonthlyBRL.",
        sourceFile: "src/constants/leadership.ts",
        sourceSheetOrTab: "BACKOFFICE_CONFIG",
        sourceRowOrCellRef: "BACKOFFICE_CONFIG[8]",
        sourceNotes: "Financial analyst. 2 headcount from launch.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "Assistente Financeiro",
        normalizedRoleId: "finance_assistant",
        roleFamily: "Backoffice",
        layer: "C",
        regime: null,
        division: null,
        areaOrFunction: "Backoffice",
        gradeBandApplicability: null,
        yearApplicability: 2031,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: "1 from 2031",
        headcountProgression: [[2031, 1]],
        rawGrossMonthlyBRL: 2862.6265,
        rawLaborChargesMonthlyBRL: 1388.37,
        rawBenefitsMonthlyBRL: 704.9656,
        monthlySalaryBRL: 2862.6265,
        monthlyTotalCostBRL: null,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOLHA_DIRETA",
        benefitsOrChargesNotes:
          "Three separate monthly components in source. See rawGrossMonthlyBRL, rawLaborChargesMonthlyBRL, rawBenefitsMonthlyBRL.",
        sourceFile: "src/constants/leadership.ts",
        sourceSheetOrTab: "BACKOFFICE_CONFIG",
        sourceRowOrCellRef: "BACKOFFICE_CONFIG[9]",
        sourceNotes:
          "Portuguese-only label in source. Activated 2031. Audit flags mixed-language label. Finance review should confirm role scope and activation trigger.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "HR Analyst",
        normalizedRoleId: "hr",
        roleFamily: "Backoffice",
        layer: "C",
        regime: null,
        division: null,
        areaOrFunction: "Backoffice",
        gradeBandApplicability: null,
        yearApplicability: 2028,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: "1 from 2028",
        headcountProgression: [[2028, 1]],
        rawGrossMonthlyBRL: 5614.0,
        rawLaborChargesMonthlyBRL: 2722.79,
        rawBenefitsMonthlyBRL: 501.15,
        monthlySalaryBRL: 5614.0,
        monthlyTotalCostBRL: null,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOLHA_DIRETA",
        benefitsOrChargesNotes:
          "Three separate monthly components in source. See rawGrossMonthlyBRL, rawLaborChargesMonthlyBRL, rawBenefitsMonthlyBRL.",
        sourceFile: "src/constants/leadership.ts",
        sourceSheetOrTab: "BACKOFFICE_CONFIG",
        sourceRowOrCellRef: "BACKOFFICE_CONFIG[10]",
        sourceNotes: "Human resources function. Campus-wide.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "School Secretary",
        normalizedRoleId: "secretary",
        roleFamily: "Backoffice",
        layer: "C",
        regime: null,
        division: null,
        areaOrFunction: "Backoffice",
        gradeBandApplicability: null,
        yearApplicability: 2028,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: "1 from 2028",
        headcountProgression: [[2028, 1]],
        rawGrossMonthlyBRL: 4206.2,
        rawLaborChargesMonthlyBRL: 2040.01,
        rawBenefitsMonthlyBRL: 845.19,
        monthlySalaryBRL: 4206.2,
        monthlyTotalCostBRL: null,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOLHA_DIRETA",
        benefitsOrChargesNotes:
          "Three separate monthly components in source. See rawGrossMonthlyBRL, rawLaborChargesMonthlyBRL, rawBenefitsMonthlyBRL.",
        sourceFile: "src/constants/leadership.ts",
        sourceSheetOrTab: "BACKOFFICE_CONFIG",
        sourceRowOrCellRef: "BACKOFFICE_CONFIG[11]",
        sourceNotes: "School secretariat function. Campus-wide.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      // ── SPECIALISTS (Layer D) ─────────────────────────────────────────────
      {
        sourceRoleLabel: "After School Educator",
        normalizedRoleId: "after_school",
        roleFamily: "Specialists",
        layer: "D",
        regime: "shared specialist",
        division: null,
        areaOrFunction: "Specialists",
        gradeBandApplicability: null,
        yearApplicability: 2028,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: "1 from 2028",
        headcountProgression: [[2028, 1]],
        rawGrossMonthlyBRL: 15247.55,
        rawLaborChargesMonthlyBRL: 7395.06,
        rawBenefitsMonthlyBRL: 1159.83,
        monthlySalaryBRL: 15247.55,
        monthlyTotalCostBRL: null,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOPAG_DIRETO",
        benefitsOrChargesNotes:
          "Three separate monthly components in source. See rawGrossMonthlyBRL, rawLaborChargesMonthlyBRL, rawBenefitsMonthlyBRL.",
        sourceFile: "src/constants/leadership.ts",
        sourceSheetOrTab: "SPECIALISTS_CONFIG",
        sourceRowOrCellRef: "SPECIALISTS_CONFIG[0]",
        sourceNotes:
          "Shared specialist (campus-wide after-school program). FOPAG_DIRETO. Salary matches Master Educator gross rate.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "Arts Educator",
        normalizedRoleId: "arts",
        roleFamily: "Specialists",
        layer: "D",
        regime: "shared specialist",
        division: null,
        areaOrFunction: "Specialists",
        gradeBandApplicability: null,
        yearApplicability: 2028,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: "1 from 2028; 2 from 2031",
        headcountProgression: [
          [2028, 1],
          [2031, 2],
        ],
        rawGrossMonthlyBRL: 15247.55,
        rawLaborChargesMonthlyBRL: 7395.06,
        rawBenefitsMonthlyBRL: 1159.83,
        monthlySalaryBRL: 15247.55,
        monthlyTotalCostBRL: null,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOPAG_DIRETO",
        benefitsOrChargesNotes:
          "Three separate monthly components in source. See rawGrossMonthlyBRL, rawLaborChargesMonthlyBRL, rawBenefitsMonthlyBRL.",
        sourceFile: "src/constants/leadership.ts",
        sourceSheetOrTab: "SPECIALISTS_CONFIG",
        sourceRowOrCellRef: "SPECIALISTS_CONFIG[1]",
        sourceNotes:
          "Shared specialist. Headcount ramp: 1 from 2028, 2 from 2031. Salary matches Master Educator gross rate.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "Body & Movement Educator",
        normalizedRoleId: "body",
        roleFamily: "Specialists",
        layer: "D",
        regime: "shared specialist",
        division: null,
        areaOrFunction: "Specialists",
        gradeBandApplicability: null,
        yearApplicability: 2028,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: "1 from 2028; 2 from 2031",
        headcountProgression: [
          [2028, 1],
          [2031, 2],
        ],
        rawGrossMonthlyBRL: 15247.55,
        rawLaborChargesMonthlyBRL: 7395.06,
        rawBenefitsMonthlyBRL: 1159.83,
        monthlySalaryBRL: 15247.55,
        monthlyTotalCostBRL: null,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOPAG_DIRETO",
        benefitsOrChargesNotes:
          "Three separate monthly components in source. See rawGrossMonthlyBRL, rawLaborChargesMonthlyBRL, rawBenefitsMonthlyBRL.",
        sourceFile: "src/constants/leadership.ts",
        sourceSheetOrTab: "SPECIALISTS_CONFIG",
        sourceRowOrCellRef: "SPECIALISTS_CONFIG[2]",
        sourceNotes:
          "Shared specialist. Headcount ramp: 1 from 2028, 2 from 2031. Salary matches Master Educator gross rate.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "Music Educator",
        normalizedRoleId: "music",
        roleFamily: "Specialists",
        layer: "D",
        regime: "shared specialist",
        division: null,
        areaOrFunction: "Specialists",
        gradeBandApplicability: null,
        yearApplicability: 2028,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: "1 from 2028; 2 from 2031",
        headcountProgression: [
          [2028, 1],
          [2031, 2],
        ],
        rawGrossMonthlyBRL: 15247.55,
        rawLaborChargesMonthlyBRL: 7395.06,
        rawBenefitsMonthlyBRL: 1159.83,
        monthlySalaryBRL: 15247.55,
        monthlyTotalCostBRL: null,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOPAG_DIRETO",
        benefitsOrChargesNotes:
          "Three separate monthly components in source. See rawGrossMonthlyBRL, rawLaborChargesMonthlyBRL, rawBenefitsMonthlyBRL.",
        sourceFile: "src/constants/leadership.ts",
        sourceSheetOrTab: "SPECIALISTS_CONFIG",
        sourceRowOrCellRef: "SPECIALISTS_CONFIG[3]",
        sourceNotes:
          "Shared specialist. Headcount ramp: 1 from 2028, 2 from 2031. Salary matches Master Educator gross rate.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "Learning Exp Designer",
        normalizedRoleId: "led",
        roleFamily: "Specialists",
        layer: "D",
        regime: "shared specialist",
        division: null,
        areaOrFunction: "Specialists",
        gradeBandApplicability: null,
        yearApplicability: 2028,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue:
          "1 from 2028; 2 from 2031; 3 from 2034; 4 from 2037",
        headcountProgression: [
          [2028, 1],
          [2031, 2],
          [2034, 3],
          [2037, 4],
        ],
        rawGrossMonthlyBRL: 15992.88,
        rawLaborChargesMonthlyBRL: 7756.55,
        rawBenefitsMonthlyBRL: 1162.98,
        monthlySalaryBRL: 15992.88,
        monthlyTotalCostBRL: null,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOLHA_DIRETA",
        benefitsOrChargesNotes:
          "Three separate monthly components in source. See rawGrossMonthlyBRL, rawLaborChargesMonthlyBRL, rawBenefitsMonthlyBRL.",
        sourceFile: "src/constants/leadership.ts",
        sourceSheetOrTab: "SPECIALISTS_CONFIG",
        sourceRowOrCellRef: "SPECIALISTS_CONFIG[4]",
        sourceNotes:
          "Learning Experience Designer (abbreviated in source). Shared specialist. Headcount grows with each division opening (2028→1, 2031→2, 2034→3, 2037→4). Salary ~5% above Master Educator rate per audit.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "HS Educator Pool",
        normalizedRoleId: "hs_pool",
        roleFamily: "Specialists",
        layer: "D",
        regime: "hs pool",
        division: "High School",
        areaOrFunction: "Specialists",
        gradeBandApplicability: ["g9", "g10", "g11", "g12"],
        yearApplicability: 2034,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: "4 from 2034; 8 from 2036",
        headcountProgression: [
          [2034, 4],
          [2036, 8],
        ],
        rawGrossMonthlyBRL: 15247.55,
        rawLaborChargesMonthlyBRL: 7395.06,
        rawBenefitsMonthlyBRL: 1159.83,
        monthlySalaryBRL: 15247.55,
        monthlyTotalCostBRL: null,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOLHA_DIRETA",
        benefitsOrChargesNotes:
          "Three separate monthly components in source. See rawGrossMonthlyBRL, rawLaborChargesMonthlyBRL, rawBenefitsMonthlyBRL.",
        sourceFile: "src/constants/leadership.ts",
        sourceSheetOrTab: "SPECIALISTS_CONFIG",
        sourceRowOrCellRef: "SPECIALISTS_CONFIG[5]",
        sourceNotes:
          "Pool of 4 Master Educators hired when g9 opens (2034); 4 more added at 2036 → pool of 8. Covers all HS grades (g9–g12). g10 and g12 have zero incremental cost (shared pool). Source label is a pool designation, not a person title. Salary matches Master Educator gross rate.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      // ── TEACHING TIERS — compensation inputs, not standalone role records ──
      {
        sourceRoleLabel: "Associate Educator",
        normalizedRoleId: "associate",
        roleFamily: "TeachingTier",
        layer: null,
        regime: null,
        division: null,
        areaOrFunction: "TeachingInstruction",
        gradeBandApplicability: null,
        yearApplicability: null,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: null,
        headcountProgression: null,
        rawGrossMonthlyBRL: 7763.46,
        rawLaborChargesMonthlyBRL: 3765.28,
        rawBenefitsMonthlyBRL: 1128.1,
        monthlySalaryBRL: 7763.46,
        monthlyTotalCostBRL: 12656.84,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only_for_monthlySalaryBRL",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOPAG_DIRETO",
        benefitsOrChargesNotes:
          "monthlyTotalCostBRL=12656.84 is the explicit totalCost field in EDUCATOR_LEVELS (= grossMonthly + laborChargesMonthly + benefitsMonthly). Annualization requires a per-section FTE count not stored on this record.",
        sourceFile: "src/constants/teaching.ts",
        sourceSheetOrTab: "EDUCATOR_LEVELS",
        sourceRowOrCellRef: "EDUCATOR_LEVELS[0]",
        sourceNotes:
          "TEACHING TIER INPUT — not a standalone payroll role record. FTE and activationYear not stored in source. Finance review must confirm: tier rate applicability for 2028+, grade/section assignment, and whether rates are current.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "Specialist Educator",
        normalizedRoleId: "specialist",
        roleFamily: "TeachingTier",
        layer: null,
        regime: null,
        division: null,
        areaOrFunction: "TeachingInstruction",
        gradeBandApplicability: null,
        yearApplicability: null,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: null,
        headcountProgression: null,
        rawGrossMonthlyBRL: 10229.37,
        rawLaborChargesMonthlyBRL: 4961.24,
        rawBenefitsMonthlyBRL: 1138.56,
        monthlySalaryBRL: 10229.37,
        monthlyTotalCostBRL: 16329.17,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only_for_monthlySalaryBRL",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOPAG_DIRETO",
        benefitsOrChargesNotes:
          "monthlyTotalCostBRL=16329.17 is the explicit totalCost field in EDUCATOR_LEVELS. See Associate Educator notes.",
        sourceFile: "src/constants/teaching.ts",
        sourceSheetOrTab: "EDUCATOR_LEVELS",
        sourceRowOrCellRef: "EDUCATOR_LEVELS[1]",
        sourceNotes:
          "TEACHING TIER INPUT — not a standalone payroll role record. FTE and activationYear not stored in source.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "Master Educator",
        normalizedRoleId: "master",
        roleFamily: "TeachingTier",
        layer: null,
        regime: null,
        division: null,
        areaOrFunction: "TeachingInstruction",
        gradeBandApplicability: null,
        yearApplicability: null,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: null,
        headcountProgression: null,
        rawGrossMonthlyBRL: 15247.55,
        rawLaborChargesMonthlyBRL: 7395.06,
        rawBenefitsMonthlyBRL: 1159.83,
        monthlySalaryBRL: 15247.55,
        monthlyTotalCostBRL: 23802.44,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only_for_monthlySalaryBRL",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOPAG_DIRETO",
        benefitsOrChargesNotes:
          "monthlyTotalCostBRL=23802.44 is the explicit totalCost field in EDUCATOR_LEVELS. Note: this gross rate is also used for after_school, arts, body, music, and hs_pool in SPECIALISTS_CONFIG.",
        sourceFile: "src/constants/teaching.ts",
        sourceSheetOrTab: "EDUCATOR_LEVELS",
        sourceRowOrCellRef: "EDUCATOR_LEVELS[2]",
        sourceNotes:
          "TEACHING TIER INPUT — not a standalone payroll role record. FTE and activationYear not stored in source.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "Inspirational Educator",
        normalizedRoleId: "inspirational",
        roleFamily: "TeachingTier",
        layer: null,
        regime: null,
        division: null,
        areaOrFunction: "TeachingInstruction",
        gradeBandApplicability: null,
        yearApplicability: null,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: null,
        headcountProgression: null,
        rawGrossMonthlyBRL: 17768.85,
        rawLaborChargesMonthlyBRL: 8617.89,
        rawBenefitsMonthlyBRL: 1216.37,
        monthlySalaryBRL: 17768.85,
        monthlyTotalCostBRL: 27603.11,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only_for_monthlySalaryBRL",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOPAG_DIRETO",
        benefitsOrChargesNotes:
          "monthlyTotalCostBRL=27603.11 is the explicit totalCost field in EDUCATOR_LEVELS.",
        sourceFile: "src/constants/teaching.ts",
        sourceSheetOrTab: "EDUCATOR_LEVELS",
        sourceRowOrCellRef: "EDUCATOR_LEVELS[3]",
        sourceNotes:
          "TEACHING TIER INPUT — not a standalone payroll role record. FTE and activationYear not stored in source.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "Distinguished Educator",
        normalizedRoleId: "distinguished",
        roleFamily: "TeachingTier",
        layer: null,
        regime: null,
        division: null,
        areaOrFunction: "TeachingInstruction",
        gradeBandApplicability: null,
        yearApplicability: null,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: null,
        headcountProgression: null,
        rawGrossMonthlyBRL: 19577.98,
        rawLaborChargesMonthlyBRL: 9495.32,
        rawBenefitsMonthlyBRL: 1224.05,
        monthlySalaryBRL: 19577.98,
        monthlyTotalCostBRL: 30297.35,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only_for_monthlySalaryBRL",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOPAG_DIRETO",
        benefitsOrChargesNotes:
          "monthlyTotalCostBRL=30297.35 is the explicit totalCost field in EDUCATOR_LEVELS.",
        sourceFile: "src/constants/teaching.ts",
        sourceSheetOrTab: "EDUCATOR_LEVELS",
        sourceRowOrCellRef: "EDUCATOR_LEVELS[4]",
        sourceNotes:
          "TEACHING TIER INPUT — not a standalone payroll role record. FTE and activationYear not stored in source.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      // ── TEACHING SUPPORT — per-section cost inputs, not standalone role records ──
      {
        sourceRoleLabel: "Learning Assistant",
        normalizedRoleId: "learning_assistant",
        roleFamily: "TeachingSupport",
        layer: null,
        regime: null,
        division: null,
        areaOrFunction: "TeachingSupport",
        gradeBandApplicability: null,
        yearApplicability: null,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: null,
        headcountProgression: null,
        rawGrossMonthlyBRL: 4595.88,
        rawLaborChargesMonthlyBRL: 2229.0,
        rawBenefitsMonthlyBRL: 997.19,
        monthlySalaryBRL: 4595.88,
        monthlyTotalCostBRL: 7822.07,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only_for_monthlySalaryBRL",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOPAG_DIRETO",
        benefitsOrChargesNotes:
          "monthlyTotalCostBRL=7822.07 is the explicit LEARNING_ASSISTANT_COST constant (= grossMonthly + laborChargesMonthly + benefitsMonthly). Section-count multiplier not stored on this record.",
        sourceFile: "src/constants/teaching.ts",
        sourceSheetOrTab: "LEARNING_ASSISTANT_DETAIL",
        sourceRowOrCellRef: "LEARNING_ASSISTANT_DETAIL / LEARNING_ASSISTANT_COST",
        sourceNotes:
          "TEACHING SUPPORT INPUT — not a standalone payroll role record. Per-section count depends on staffing rules not stored here. activationYear not stored. Finance review must confirm section-applicability rules.",
        needsFinanceReview: false,
        calculationReady: false,
      },
      {
        sourceRoleLabel: "Learning Monitor",
        normalizedRoleId: "learning_monitor",
        roleFamily: "TeachingSupport",
        layer: null,
        regime: null,
        division: null,
        areaOrFunction: "TeachingSupport",
        gradeBandApplicability: null,
        yearApplicability: null,
        scenarioApplicability: null,
        fteOrHeadcountSourceValue: null,
        headcountProgression: null,
        rawGrossMonthlyBRL: 4060.63,
        rawLaborChargesMonthlyBRL: 1969.41,
        rawBenefitsMonthlyBRL: 994.92,
        monthlySalaryBRL: 4060.63,
        monthlyTotalCostBRL: 7024.96,
        annualSalaryBRL: null,
        annualTotalCostBRL: null,
        costBasis: "gross_monthly_salary_only_for_monthlySalaryBRL",
        includesBenefitsOrCharges: false,
        allocationCategory: "FOPAG_DIRETO",
        benefitsOrChargesNotes:
          "monthlyTotalCostBRL=7024.96 is the explicit LEARNING_MONITOR_COST constant (= grossMonthly + laborChargesMonthly + benefitsMonthly). Section-count multiplier not stored on this record.",
        sourceFile: "src/constants/teaching.ts",
        sourceSheetOrTab: "LEARNING_MONITOR_DETAIL",
        sourceRowOrCellRef: "LEARNING_MONITOR_DETAIL / LEARNING_MONITOR_COST",
        sourceNotes:
          "TEACHING SUPPORT INPUT — not a standalone payroll role record. Per-section count depends on staffing rules not stored here. activationYear not stored. Finance review must confirm section-applicability rules.",
        needsFinanceReview: false,
        calculationReady: false,
      },
    ],
  };

export const PAYROLL_ROLE_COST_SOURCE_RECORDS: PayrollRoleCostSourceRecord[] =
  PAYROLL_ROLE_COST_SOURCE_DATA.records;
